source 'https://github.com/CocoaPods/Specs.git'

target 'AlertView', :exclusive => true do
  pod "AlertView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "AlertView", :path => "../"

  pod 'FBSnapshotTestCase'
end
